name: Build Example

on:
  workflow_dispatch:

jobs:
  checkout-example:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ['20.x']

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      
      - run: npm install
      - run: npm run build --if-present
      - name: Better Test Reports Action
        uses: mridang/action-test-reporter@v1.5.0
      - run: npm test-- --coverage
      

      - name: Code Coverage Report
        uses: mridang/action-test-reporter@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          coverage-file: ./coverage/clover.xml # Path to your clover, cobertura, jacoco, or lcov file
          working-directory: ./
