name: Docker Example

on:
  workflow_dispatch:

jobs:
  checkout-example:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ['20.x']

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      
      - run: npm install
      - run: npm run build --if-present
      - run: npm test -- --coverage
      - name: Better Test Reports Action
        uses: mridang/action-test-reporter@v1.5.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          coverage-file: ./coverage/clover.xml # Path to your clover, cobertura, jacoco, or lcov file
          working-directory: ./
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.USERNAME }}
          password: ${{ secrets.TOKEN-dockerhubtoken }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: user/app:latest
